### ISSUE TITLE
Some errors 

### ISSUE THREAD

**Issue by cipher387** [datacoon/metawarc#1]
python  metawarc metadata digital.gov.ru.warc.gz
Traceback (most recent call last):
  File "/home/gitpod/.pyenv/versions/3.8.12/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/gitpod/.pyenv/versions/3.8.12/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/workspace/metawarc/metawarc/__main__.py", line 18, in <module>
    main()
  File "/workspace/metawarc/metawarc/__main__.py", line 10, in main
    from .core import cli
ImportError: attempted relative import with no known parent package

**Comment by ivbeg** [comment]
@cipher387 Hi! Is it after installation using "pip install metawarc" or it's latest code from github?

**Comment by cipher387** [comment]
latest code from GitHub

**Comment by ivbeg** [comment]
@cipher387 you should launch "metawarc metadata digital.gov.ru.warc.gz" or "python -m metawarc metadata digital.gov.ru.warc.gz"

**Comment by ivbeg** [comment]
Thanks for the report.

The original traceback (`attempted relative import with no known parent package`) comes from running the package path as a script (`python metawarc ...`). That does not set a package context. The supported entry points are:

```
metawarc ...
# or
python -m metawarc ...
```

Those work on current master / PyPI 2.0.1. The old `metadata` subcommand has also been replaced by the 2.x workspace flow (`index`, `index-content`, `analyze`, etc.).

Closing as no longer actionable for the current release. Please open a new issue with the exact command and traceback if something still fails on 2.0.1+.
