### ISSUE TITLE
NameError: name 'unknown' is not defined

### ISSUE THREAD

**Issue by gsv70** [datacoon/metawarc#5]
$ metawarc dump -e mp3,ogg -o audio
Wrote 790a1d27-01c8-460a-968b-d2c6cf22aa31.mp3, url https://cdn.echo.msk.ru/snd/2022-03-02-osoboe-1908-3631063.mp3
...
...
Wrote f9204bd8-c662-4cff-9261-df686e6383d6.mp3, url https://cdn.echo.msk.ru/snd/2021-10-25-personalnovash-1505-sd-3551552.mp3
Traceback (most recent call last):
  File "/home/me/.local/bin/metawarc", line 8, in <module>
    sys.exit(main())
  File "/home/me/.local/lib/python3.10/site-packages/metawarc/__main__.py", line 12, in main
    exit_status = cli()
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/me/.local/lib/python3.10/site-packages/metawarc/core.py", line 215, in dump
    acmd.dump(mimes=mimes, exts=exts, query=query, output=output)
  File "/home/me/.local/lib/python3.10/site-packages/metawarc/cmds/dump.py", line 140, in dump
    filename = record.warc_id + '.' + get_ext_from_content_type(record.content_type)
  File "/home/me/.local/lib/python3.10/site-packages/metawarc/cmds/dump.py", line 62, in get_ext_from_content_type
    return unknown
NameError: name 'unknown' is not defined

**In my WARC file (Плющев выкладывал ссылку в телеграм) exist 'audio/mp3'
I add 'audio/mp3' : 'mp3', in  MIME_EXT_MAP and error is disappear
Thanks**

example of "bad" record in db
INSERT INTO record VALUES(3483,'920138fa-d58c-4d15-b3bb-c8521c93199b','audio/mp3',200,'https://cdn.echo.msk.ru/snd/2009-03-06-
vlast-2000.mp3','2009-03-06-vlast-2000.mp3','mp3','echo.msk.ru.warc.gz',10075372887,13434884,13991489,'"{\"Server\": \"nginx\"
, \"Date\": \"Thu, 03 Mar 2022 08:36:36 GMT\", \"Content-Type\": \"audio/mp3\", \"Content-Length\": \"13990981\", \"Connection
\": \"keep-alive\", \"Last-Modified\": \"Fri, 29 Oct 2021 19:44:09 GMT\", \"x-rgw-object-type\": \"Normal\", \"ETag\": \"\\\"5
dcebd6aca8b9f6b9579dacf4ccd03ce\\\"\", \"x-amz-request-id\": \"tx0000000000000106f1bbf-0061e352aa-3e13cf9-dt2\", \"Cache\": \"
MISS\", \"X-Cached-Since\": \"2022-01-15T23:03:06+00:00\", \"Access-Control-Allow-Origin\": \"*\", \"X-ID\": \"rtc-up-gc5\", \
"Accept-Ranges\": \"bytes\", \"X-SHARD\": \"rtc-shard0-default_443\"}"');

**Comment by ivbeg** [comment]
Thanks, I've fixed it in the most recent code. I will update release too soon.
